
# We want a workspace so we can have seperated projects
#
# we need this because proc-macros have to be in their own crate I guess
[workspace]
members = [
        "kernel",
        "hook",
]
default-members = [ "kernel" ]