[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "riscv64imac-unknown-none-elf"
rustflags = ["-C", "link-args=-Tkernel.ld --no-pie", "-C", "relocation-model=static"
]

# [target.riscv64imac-unknown-none-elf]
# runner = "./qemu-wrapper.sh riscv64"
# Running now requires external wrapping, see saneboot for the prefered method with uboot and opensbi.
